
# Application Name
spring.application.name=journalApp

# MongoDB Atlas Connection
#spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.uri=mongodb+srv://Cluster35146:SG5OYkxndFR5@cluster35146.eirncun.mongodb.net/journaldb
spring.data.mongodb.auto-index-creation=true
# Server
server.port=8080

# Logging
logging.level.org.springframework=INFO