# Application profile
spring:
  profiles:
    active: dev


#. package com.edigest.journalApp.service;
logging:
  level:
    com:
      edigest:
        journalApp:
          service:
            UserService: OFF


# log for all
#logging:
 # level:
 #   root: ERROR
